config/routes.rb
Rails.application.routes.draw do
  resources :partners, only: [:index, :show]
  resources :child_fatalities, only: [:index, :show], path: 'facts-figures'

  root to: redirect('http://hcflgov.net/en/government/boards-and-committees/a-d/blue-ribbon-committee-for-child-safety')
end

app/models/partner.rb
class Partner < ApplicationRecord

	default_scope { order(name: :asc) }
	paginates_per 20

	# geocoded_by :address
	# after_validation { geocode_conditionals(:address) }
	#
	# def geocode_conditionals(attribute)
	# 	self.geocode if self.send("#{attribute}_changed?") || self.latitude.nil? || self.longitude.nil?
	# end



end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  layout false, only: [:show]
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.page(params[:page])
	 @page_title = 'Partners'
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url, notice: 'Partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:name, :description, :address, :latitude, :longitude, :phone)
    end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= form_for(partner) do |f| %>
  <% if partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% partner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<h1>Editing Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div id="map" class="embed-responsice embed-responsive-16by9 thumbnail"></div>
	</div>
</div>

<div class="table-responsive">
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>Name</th>
				<th>Address</th>
			</tr>
		</thead>

		<tbody id="brc-partners">
			<% @partners.each do |partner| %>
			<tr class="brc-partner" data-path="<%= url_for partner %>" data-latitude="<%= partner.latitude %>" data-longitude="<%= partner.longitude %>">
				<td><%= link_to partner.name, partner %></td>
				<td><%= partner.address %></td>
			</tr>
			<% end %>
		</tbody>

	</table>
</div>

<div class="pagination-container text-center">
	<%= paginate @partners %>
</div>

<!-- Modal -->
<div class="modal fade" id="partnerModal" tabindex="-1" role="dialog" aria-labelledby="partnerModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content"></div>
	</div>
</div>

app/views/partners/new.html.erb
<h1>New Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<header class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="partnerModalLabel">
		<%= @partner.name %>
	</h4>
</header>

<div class="modal-body">
	<% if @partner.address.present? %>
	<p>
		<strong>Address:</strong>
		<%= @partner.address %>
	</p>
	<% end %>

	<% if @partner.description.present? %>
	<p>
		<strong>Description:</strong>
		<%= @partner.description %>
	</p>
	<% end %>

	<% if @partner.phone.present? %>
	<p>
		<strong>Phone:</strong>
		<%= @partner.phone %>
	</p>
	<% end %>

</div>

<footer class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</footer>