config/routes.rb
Rails.application.routes.draw do
  resources :partners, only: [:index, :show]
  resources :child_fatalities, only: [:index, :show], path: 'facts-figures'

  root to: redirect('http://hcflgov.net/en/government/boards-and-committees/a-d/blue-ribbon-committee-for-child-safety')
end

app/models/child_fatality.rb
require 'open-uri'

class ChildFatality < ApplicationRecord

	default_scope { where(county: 'Hillsborough').order(dod: :desc) }

	def self.filter(params)
		where parameter_filters(params)
	end

	def self.group_counts(group_by)
		if Rails.env.production?
			# postgresql
			group_by = group_by == :year ? "extract(year from dod)" : group_by
		else
			# sqlite
			group_by = group_by == :year ? "strftime('%Y', dod)" : group_by
		end
		group(group_by).reorder(group_by).count
	end

	def self.scan
		self.scan! if self.needs_scan?
	end

	def self.scan!
		self.destroy_all
		create_arr = []
		xml_doc = Nokogiri::HTML(open("http://www.dcf.state.fl.us/childfatality/data.xml"))
		xml_doc.xpath("//record").each do |record|
			if record.xpath('county').text == 'Hillsborough'
				create_arr << {
					dod: Date.strptime(record.xpath('dod').text,"%m/%d/%Y"),
					gender: record.xpath('gender').text,
					age: record.xpath('age').text.to_i,
					county: record.xpath('county').text,
					priorChild: yesno_to_bool(record.xpath('priorchild').text),
					priorVerChild: yesno_to_bool(record.xpath('priorverchild').text),
					priorTwelve: yesno_to_bool(record.xpath('prior12').text),
					priorFive: yesno_to_bool(record.xpath('prior5').text),
					priorFiveServices: yesno_to_bool(record.xpath('prior5services').text),
					causal: record.xpath('causal').text,
					narrative: record.xpath('narrative').text
				}
			end
		end
		self.create create_arr
	rescue
		return false
	end

	def self.needs_scan?
		self.any? ? (Time.now - self.last_updated) > 5.days : true
	end

	def self.last_updated
		self.any? ? order(updated_at: :desc).first.try(:updated_at) : Time.now
	end

	private

	def self.yesno_to_bool(test)
		test.downcase == 'yes' ? true : false
	end

	def self.parameter_filters(params)
		filters = []
		if Rails.env.production?
			# postgresql
			filters << "extract(year from dod) = '#{params[:year]}'" if params[:year].present?
		else
			# sqlite
			filters << "strftime('%Y', dod) = '#{params[:year]}'" if params[:year].present?
		end
		filters << "age = #{params[:age]}" if params[:age].present?
		filters << "causal LIKE '#{params[:causal]}'" if params[:causal].present?
		filters << "gender LIKE '#{params[:gender]}'" if params[:gender].present?
		filters << "county LIKE '#{params[:county]}'" if params[:county].present?
		filters.join(' AND ').to_s
	end

end

app/controllers/child_fatalities_controller.rb
class ChildFatalitiesController < ApplicationController
  before_action :set_child_fatality, only: [:show, :edit, :update, :destroy]
  before_action :needs_to_scan?

  # GET /child_fatalities
  # GET /child_fatalities.json
  def index
	 @page_title = 'Facts & Figures'
    @child_fatalities = ChildFatality.filter params
  end

  # GET /child_fatalities/1
  # GET /child_fatalities/1.json
  def show
  end

  # GET /child_fatalities/new
  def new
    @child_fatality = ChildFatality.new
  end

  # GET /child_fatalities/1/edit
  def edit
  end

  # POST /child_fatalities
  # POST /child_fatalities.json
  def create
    @child_fatality = ChildFatality.new(child_fatality_params)

    respond_to do |format|
      if @child_fatality.save
        format.html { redirect_to @child_fatality, notice: 'Child fatality was successfully created.' }
        format.json { render :show, status: :created, location: @child_fatality }
      else
        format.html { render :new }
        format.json { render json: @child_fatality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /child_fatalities/1
  # PATCH/PUT /child_fatalities/1.json
  def update
    respond_to do |format|
      if @child_fatality.update(child_fatality_params)
        format.html { redirect_to @child_fatality, notice: 'Child fatality was successfully updated.' }
        format.json { render :show, status: :ok, location: @child_fatality }
      else
        format.html { render :edit }
        format.json { render json: @child_fatality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /child_fatalities/1
  # DELETE /child_fatalities/1.json
  def destroy
    @child_fatality.destroy
    respond_to do |format|
      format.html { redirect_to child_fatalities_url, notice: 'Child fatality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child_fatality
      @child_fatality = ChildFatality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_fatality_params
      params.require(:child_fatality).permit(:dod, :gender, :age, :county, :priorChild, :priorVerChild, :priorTwelve, :priorFive, :priorFiveServices, :causal, :narrative)
    end

	 def needs_to_scan?
	 	ChildFatality.scan
	 end
end

app/helpers/child_fatalities_helper.rb
module ChildFatalitiesHelper

	def jumper(column, options={})
		return year_jumper if column == :year
		options = ChildFatality.all.map{ |record|
			jump_url = url_for(params.except(:action, :controller).merge(column => record.send(column)).permit!)
			[
				record.send(column),
				record.send(column),
				data: {jumper: jump_url}
			]
		}.uniq.sort
		options.unshift [column.capitalize, nil, data: {jumper: url_for(params.except(:action, :controller, column.to_sym).permit!)}]
		select_tag column, options_for_select( options, params[column] ), class: 'jumper-select form-control input-sm'
	end

	def year_jumper
		options = ChildFatality.all.map{ |record|
			jump_url = url_for(params.except(:action, :controller).merge(year: record.dod.year).permit!)
			[
				record.dod.year,
				record.dod.year,
				data: {jumper: jump_url}
			]
		}.uniq.sort.reverse
		options.unshift ['Year', 'test', data: {jumper: url_for(params.except(:action, :controller, :year).permit!)}]
		select_tag 'year', options_for_select( options, params[:year] ), class: 'jumper-select form-control input-sm'
	end

end

app/views/child_fatalities/_form.html.erb
<%= form_for(child_fatality) do |f| %>
  <% if child_fatality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(child_fatality.errors.count, "error") %> prohibited this child_fatality from being saved:</h2>

      <ul>
      <% child_fatality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dod %>
    <%= f.date_select :dod %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :county %>
    <%= f.text_field :county %>
  </div>

  <div class="field">
    <%= f.label :priorChild %>
    <%= f.check_box :priorChild %>
  </div>

  <div class="field">
    <%= f.label :priorVerChild %>
    <%= f.check_box :priorVerChild %>
  </div>

  <div class="field">
    <%= f.label :priorTwelve %>
    <%= f.check_box :priorTwelve %>
  </div>

  <div class="field">
    <%= f.label :priorFive %>
    <%= f.check_box :priorFive %>
  </div>

  <div class="field">
    <%= f.label :priorFiveServices %>
    <%= f.check_box :priorFiveServices %>
  </div>

  <div class="field">
    <%= f.label :causal %>
    <%= f.text_field :causal %>
  </div>

  <div class="field">
    <%= f.label :narrative %>
    <%= f.text_area :narrative %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/child_fatalities/edit.html.erb
<h1>Editing Child Fatality</h1>

<%= render 'form', child_fatality: @child_fatality %>

<%= link_to 'Show', @child_fatality %> |
<%= link_to 'Back', child_fatalities_path %>

app/views/child_fatalities/index.html.erb
<header class="page-header">
	<%= render 'child_fatalities/partials/filters' -%>
</header>

<p id="notice"><%= notice %></p>

<% if @child_fatalities.any? %>

<p class="small text-right">
	<em class="label label-info">
		Last Updated: <%= @child_fatalities.last_updated.to_formatted_s(:long) -%>
	</em>
</p>

<%= render 'child_fatalities/partials/charts' -%>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th></th>
				<th>Death</th>
				<th>Gender</th>
				<th>Age</th>
				<th>Causal</th>
				<th>Narrative</th>
			</tr>
		</thead>

		<tbody>
			<% @child_fatalities.each do |child_fatality| %>
			<tr>
				<td><%#= link_to fa_icon('info-circle fw'), url_for(child_fatality), class: 'btn btn-default btn-sm' %></td>
				<td class="nowrap"><%= link_to child_fatality.dod, params.merge(year: child_fatality.dod.year).permit! %></td>
				<td class="nowrap"><%= link_to child_fatality.gender, params.merge(gender: child_fatality.gender).permit! %></td>
				<td class="nowrap"><%= link_to child_fatality.age , params.merge(age: child_fatality.age).permit! %></td>
				<td><%= link_to child_fatality.causal, params.merge(causal: child_fatality.causal).permit! %></td>
				<td><%= child_fatality.narrative %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>


<% else %>
<p class="text-center h4">
	<em>
		No Records
	</em>
</p>
<% end %>

<p class="small text-right">
	<em class="label label-info">
		Last Updated: <%= @child_fatalities.last_updated.to_formatted_s(:long) -%>
	</em>
</p>

<script type="text/javascript">
<%= render partial: 'child_fatalities/partials/script', formats: [:js] -%>
</script>

app/views/child_fatalities/new.html.erb
<h1>New Child Fatality</h1>

<%= render 'form', child_fatality: @child_fatality %>

<%= link_to 'Back', child_fatalities_path %>

app/views/child_fatalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dod:</strong>
  <%= @child_fatality.dod %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @child_fatality.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @child_fatality.age %>
</p>

<p>
  <strong>County:</strong>
  <%= @child_fatality.county %>
</p>

<p>
  <strong>Priorchild:</strong>
  <%= @child_fatality.priorChild %>
</p>

<p>
  <strong>Priorverchild:</strong>
  <%= @child_fatality.priorVerChild %>
</p>

<p>
  <strong>Priortwelve:</strong>
  <%= @child_fatality.priorTwelve %>
</p>

<p>
  <strong>Priorfive:</strong>
  <%= @child_fatality.priorFive %>
</p>

<p>
  <strong>Priorfiveservices:</strong>
  <%= @child_fatality.priorFiveServices %>
</p>

<p>
  <strong>Causal:</strong>
  <%= @child_fatality.causal %>
</p>

<p>
  <strong>Narrative:</strong>
  <%= @child_fatality.narrative %>
</p>

<%#= link_to 'Edit', edit_child_fatality_path(@child_fatality) %>
<%= link_to 'Back', child_fatalities_path %>